plugins {
    id 'com.android.application'
}

android {
    namespace 'xyz.sixseven.ttt'
    compileSdk 34

    defaultConfig {
        applicationId "xyz.sixseven.ttt"
        minSdk 21
        targetSdk 34
        versionCode 67
        versionName "6.7"
    }

    buildTypes {
        release {
            minifyEnabled false
            // подписываем отладочным ключом, иначе APK не поставить с телефона
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}
