plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.triglyph'
    compileSdk 34

    defaultConfig {
        applicationId "ai.triglyph"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // подписываем отладочным ключом: иначе APK нельзя поставить с телефона
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}
